secrets = "s47Vm9FxllNnLP6YolDR4dadYLkrxy5gzp6O5Lg2+0bX0MNwGsA5eObMCCLQPYs0GquhQticS+bn9ldJUjogJO5m4P2vKkcXSOFbJYyg0le2wcJAhVIpgjKOn3ynQ29Wuxb6ybzIvye5hEu9taVFBZgRvh1Z3cEa1KL774P2w6g37ehROlf8SzVVwUiFjQwuF3x+dqKrnh3yxHzd0Gx7rgLdtOPl14pgmZ7Nwa3zK0tT7fqCT3USZZEWmTVEW+0UslZXJ7u5mdoyZAE5fi951H3USB9rd8BbHZlBdl2Rgec9mE145LWi4+ih0Hb4SzZB1PgWx8Zkk0yv1J0VC03VMrgFjMK9yNLwXtfIe19sK19hdB1WiqNZjlOf2haONXZkbr/6zqK7eZD6IHVesLbAsWapCLXZOUMPibNQO9q6gegNqewQ8Cruo81PGaDQS+Narn+BY3t+gjZkzbJLuuvbcTf/Hyl9lA+tM3KsdxHAYD5DHqUwApykyRupApIHUwsYnKC7ErWfO8NObgKLyFQJnZiDdnvXr5WZoeES9rskL+7ConXI4KItBHviRXwQWTG1FH8UlpiBfSkvXQ5ixzRJlARDhUZTPkewvkwScogifNnyXSCuf6zHwCCel+ZsmTDmQoBq25uNHQre2ydMi335bf4GfleB+sBDR5hO97d2+8I="

[http]
  host = "localhost"
  port = 8080
  ssl = false

[database]
  type = "postgres"
  [database.args]
    dbname = "itpkg_dev"
    sslmode = "disable"
    user = "postgres"

[redis]
  host = "localhost"
  port = 6379
  db = 2

[elastic_search]
  host = "localhost"
  port = 9200
  index = "itpkg-dev"

[workers]
  id = "itpkg-workers"
  pool = 15
  [workers.queues]
    default = 1
    emails = 2
