secrets = "wwSkIkRMkF6LDu9O37xo1PX3hwn+3BYqz0zuV9FDuynD1x3U2R6Uv8idpgCya1rwVLjfm4geJTBmxX8p0h4TUqMTeK7Rx/qA4TnoMHO/QJ37c7hlLxcrNEhl2mVeYCjvkDm1W2BTBVYagSzymnee12ScF6tkQzkfMqemvTVcOylFmCt3kzfJUh2tdDpIeD96tmDQ78NSzIsETacoI1VGVh+H1YqFI98WFlXywP1eOamgt6S+kDsd5LlEXaIJV0Hy7O67K+du+1h+pN4d9Qvf/0tq5M4G2USV74bGLdrH8qWbRd3beZuJHmWPztWpoKVmeZz+qcBmuOmiHAGjtHbUlsboxERJ7+MHNaoUkg/CB+afxUiYs8x3KFpcYykzCcRjW4Gve75K/rqFqzWh3+9l6kYV0TPmx7BlLBAqjY6ZUQ6MYdL8CieKRyTe9VMTekH8KUxVmHhpO/ACuGWeE229Osh00r1szV0QRUdCUfMxWiNU/g3QNjNwhhYhX05eU2/QG26smZPq3oHK0luXfUNP89oMSYqIKBO9vzwAOusug9WCjREp8TtXqVwXCxvT0DV3n4OrfycyFfZHuwq/eIUSpTBHKv5GRoAxUFBVZ1/G0/ktJ/m/WAj9xGHt9ftwQI3m0+oCxHxdC1WE0X4UcQ6y1D6vICHZWLUrcfuI3K+QCP4="

[http]
  host = "localhost"
  port = 3000
  ssl = false

[database]
  type = "postgres"
  [database.args]
    dbname = "itpkg_dev"
    sslmode = "disable"
    user = "postgres"

[redis]
  host = "localhost"
  port = 6379
  db = 2

[elastic_search]
  host = "localhost"
  port = 9200
  index = "itpkg-dev"

[workers]
  id = "itpkg-workers"
  pool = 15
  [workers.queues]
    default = 1
    emails = 2
